project_id = "neqtlreqfkrxzvuxaprl"

[functions.send-whatsapp]
verify_jwt = false

[functions.process-whatsapp-queue]
verify_jwt = false

[functions.google-drive-auth]
verify_jwt = false

[functions.google-drive-operations]
verify_jwt = false
